#!/bin/sh
#
# con este hook garantizamos que el codigo cumple con que los test unitarios
# y test funcionales estan pasando satisfactoriamente
echo "[[ Executing pre-push Hook ]]"

echo "[[ Checking Linting ]]"
npm run lint
rc=$?; if [ $rc != 0 ]; then exit $rc; fi
echo "OK"

echo "[[ Checking Unit Test ]]"
# npm run tes
# rc=$?; if [ $rc != 0 ]; then exit $rc; fi
echo "OK"

echo "[[ Checking Functional Test ]]"
# npm run e2e
# rc=$?; if [ $rc != 0 ]; then exit $rc; fi
echo "OK"

echo "END"
exit 0